-- MySQL Script generated by MySQL Workbench
-- Fri Apr  8 11:42:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cook4life
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cook4life
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cook4life` DEFAULT CHARACTER SET utf8 ;
USE `db_cook4life` ;

-- -----------------------------------------------------
-- Table `db_cook4life`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cook4life`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NULL,
  `email` VARCHAR(30) NULL,
  `foto` VARCHAR(20) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cook4life`.`resep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cook4life`.`resep` (
  `id_resep` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `nama_resep` VARCHAR(25) NULL,
  `deskripsi` TEXT NULL,
  `gambar` VARCHAR(20) NULL,
  `tanggal_buat` DATETIME NULL,
  PRIMARY KEY (`id_resep`),
  INDEX `fk_resep_user1_idx` (`id_user`),
  UNIQUE INDEX `id_resep_UNIQUE` (`id_resep`),
  CONSTRAINT `fk_resep_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_cook4life`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cook4life`.`toko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cook4life`.`toko` (
  `id_toko` INT NOT NULL AUTO_INCREMENT,
  `nama_toko` VARCHAR(45) NULL,
  `alamat` VARCHAR(200) NULL,
  `latitude` VARCHAR(10) NULL,
  `longtitude` VARCHAR(11) NULL,
  `no_telp` VARCHAR(14) NULL,
  PRIMARY KEY (`id_toko`),
  UNIQUE INDEX `id_toko_UNIQUE` (`id_toko`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cook4life`.`bahan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cook4life`.`bahan` (
  `id_bahan` INT NOT NULL AUTO_INCREMENT,
  `id_resep` INT NOT NULL,
  `id_toko` INT NOT NULL,
  `nama_bahan` VARCHAR(20) NULL,
  `harga` INT NULL,
  PRIMARY KEY (`id_bahan`),
  INDEX `fk_bahan_resep1_idx` (`id_resep`),
  INDEX `fk_bahan_toko1_idx` (`id_toko`),
  UNIQUE INDEX `id_bahan_UNIQUE` (`id_bahan`),
  CONSTRAINT `fk_bahan_resep1`
    FOREIGN KEY (`id_resep`)
    REFERENCES `db_cook4life`.`resep` (`id_resep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bahan_toko1`
    FOREIGN KEY (`id_toko`)
    REFERENCES `db_cook4life`.`toko` (`id_toko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cook4life`.`langkah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cook4life`.`langkah` (
  `id_langkah` INT NOT NULL AUTO_INCREMENT,
  `id_resep` INT NOT NULL,
  `deskripsi` VARCHAR(60) NULL,
  `waktu` TINYINT NULL,
  PRIMARY KEY (`id_langkah`),
  INDEX `fk_langkah_resep1_idx` (`id_resep`),
  UNIQUE INDEX `id_langkah_UNIQUE` (`id_langkah`),
  CONSTRAINT `fk_langkah_resep1`
    FOREIGN KEY (`id_resep`)
    REFERENCES `db_cook4life`.`resep` (`id_resep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cook4life`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cook4life`.`review` (
  `id_review` INT NOT NULL,
  `id_resep` INT NOT NULL AUTO_INCREMENT,
  `rating` TINYINT NULL,
  `komentar` VARCHAR(50) NULL,
  `tanggal` DATETIME NULL,
  PRIMARY KEY (`id_review`),
  INDEX `fk_review_resep1_idx` (`id_resep`),
  UNIQUE INDEX `id_review_UNIQUE` (`id_review`),
  CONSTRAINT `fk_review_resep1`
    FOREIGN KEY (`id_resep`)
    REFERENCES `db_cook4life`.`resep` (`id_resep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
